import { Asset, AssetStatus, AssetCategory } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    name: 'Dell Latitude 7420 Laptop',
    category: AssetCategory.Laptop,
    status: AssetStatus.Assigned,
    purchaseDate: '2023-08-20',
    reimageDate: '2025-04-30',
    value: 1450.00,
    assignedTo: { name: 'Prof. Sarah Chen', email: 'sarah.chen@example.com' },
    department: 'Finance',
    location: 'North Campus - F201',
    description: 'Standard issue faculty laptop for teaching and administration. 16GB RAM, 512GB SSD.',
    serialNumber: 'AST-001',
  },
  {
    id: 'asset-2',
    name: 'Apple MacBook Pro 14"',
    category: AssetCategory.Laptop,
    status: AssetStatus.Assigned,
    purchaseDate: '2023-09-01',
    reimageDate: '2025-08-09',
    value: 2199.99,
    assignedTo: { name: 'Dr. Emily Carter', email: 'emily.carter@example.com' },
    department: 'Student Wellness',
    location: 'Lakeshore Campus - Wellness Center',
    description: 'High-performance laptop for graphic design and video editing.',
    serialNumber: 'AST-002',
  },
  {
    id: 'asset-3',
    name: 'Dell OptiPlex 7090 Desktop',
    category: AssetCategory.Desktop,
    status: AssetStatus.AwaitingReimage,
    purchaseDate: '2022-11-15',
    reimageDate: '2024-10-14',
    value: 1200.00,
    assignedTo: { name: '', email: '' },
    department: 'Registration Office',
    location: 'North Campus - Registration Office',
    description: 'Desktop for student registration and administrative tasks. Awaiting OS refresh.',
    serialNumber: 'AST-003',
  },
  {
    id: 'asset-4',
    name: 'Apple iMac 24"',
    category: AssetCategory.Desktop,
    status: AssetStatus.Assigned,
    purchaseDate: '2021-05-10',
    reimageDate: '2025-09-14',
    value: 1549.00,
    assignedTo: { name: 'Mark Roberts', email: 'mark.roberts@example.com' },
    department: 'Finance',
    location: 'North Campus - Finance Dept',
    description: 'All-in-one desktop for financial analysis.',
    serialNumber: 'AST-004',
  },
  {
    id: 'asset-5',
    name: 'Dell Inspiron 15 3000',
    category: AssetCategory.Laptop,
    status: AssetStatus.InStock,
    purchaseDate: '2024-01-10',
    reimageDate: '2025-01-14',
    value: 850.00,
    assignedTo: { name: '', email: '' },
    department: '',
    location: 'North Campus - IT Storage',
    description: 'A spare laptop available for assignment.',
    serialNumber: 'AST-005',
  },
  {
    id: 'asset-6',
    name: 'Epson PowerLite 1781W',
    category: AssetCategory.Projector,
    status: AssetStatus.InRepair,
    purchaseDate: '2021-05-10',
    reimageDate: '',
    value: 749.00,
    assignedTo: { name: '', email: '' },
    department: 'AV Services',
    location: 'AV Repair Bench',
    description: 'Portable classroom projector. Issue: Dim bulb. Sent for repair.',
    serialNumber: 'EPSON-PL-4321',
  },
   {
    id: 'asset-7',
    name: 'Lenovo ThinkPad X1',
    category: AssetCategory.Laptop,
    status: AssetStatus.AwaitingReimage,
    purchaseDate: '2022-06-15',
    reimageDate: '2024-09-30',
    value: 1800.00,
    assignedTo: { name: '', email: '' },
    department: 'IT Services',
    location: 'IT Service Desk',
    description: 'Returned from faculty, awaiting re-image for new user.',
    serialNumber: 'AST-007',
  },
];
