
import { Asset, AssetStatus, AssetCategory, AppUser } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    assetTag: 'TAG-1001',
    name: 'Dell Latitude 7420 Laptop',
    category: AssetCategory.Laptop,
    status: AssetStatus.Assigned,
    purchaseDate: '2023-08-20',
    reimageDate: '2025-04-30',
    value: 1450.00,
    assignedTo: { name: 'Prof. Sarah Chen', email: 'sarah.chen@example.com' },
    department: 'Finance',
    location: 'North Campus - F201',
    description: 'Standard issue faculty laptop for teaching and administration. 16GB RAM, 512GB SSD.',
    serialNumber: 'AST-001',
    auditLog: [
      { id: 'log-1', date: '2023-08-20T10:00:00Z', action: 'Created', details: 'Asset created in system', user: 'Admin' },
      { id: 'log-2', date: '2023-08-21T14:30:00Z', action: 'Updated', details: 'Assigned to Prof. Sarah Chen', user: 'Admin' }
    ],
  },
  {
    id: 'asset-2',
    assetTag: 'TAG-1002',
    name: 'Apple MacBook Pro 14"',
    category: AssetCategory.Laptop,
    status: AssetStatus.Assigned,
    purchaseDate: '2023-09-01',
    reimageDate: '2025-08-09',
    value: 2199.99,
    assignedTo: { name: 'Dr. Emily Carter', email: 'emily.carter@example.com' },
    department: 'Student Wellness',
    location: 'Lakeshore Campus - Wellness Center',
    description: 'High-performance laptop for graphic design and video editing.',
    serialNumber: 'AST-002',
    auditLog: [
       { id: 'log-3', date: '2023-09-01T09:15:00Z', action: 'Created', details: 'Asset created in system', user: 'Admin' }
    ],
  },
  {
    id: 'asset-3',
    assetTag: 'TAG-1003',
    name: 'Dell OptiPlex 7090 Desktop',
    category: AssetCategory.Desktop,
    status: AssetStatus.AwaitingReimage,
    purchaseDate: '2022-11-15',
    reimageDate: '2024-10-14',
    value: 1200.00,
    assignedTo: { name: '', email: '' },
    department: 'Registration Office',
    location: 'North Campus - Registration Office',
    description: 'Desktop for student registration and administrative tasks. Awaiting OS refresh.',
    serialNumber: 'AST-003',
    auditLog: [],
  },
  {
    id: 'asset-4',
    assetTag: 'TAG-1004',
    name: 'Apple iMac 24"',
    category: AssetCategory.Desktop,
    status: AssetStatus.Assigned,
    purchaseDate: '2021-05-10',
    reimageDate: '2025-09-14',
    value: 1549.00,
    assignedTo: { name: 'Mark Roberts', email: 'mark.roberts@example.com' },
    department: 'Finance',
    location: 'North Campus - Finance Dept',
    description: 'All-in-one desktop for financial analysis.',
    serialNumber: 'AST-004',
    auditLog: [],
  },
  {
    id: 'asset-5',
    assetTag: 'TAG-1005',
    name: 'Dell Inspiron 15 3000',
    category: AssetCategory.Laptop,
    status: AssetStatus.InStock,
    purchaseDate: '2024-01-10',
    reimageDate: '2025-01-14',
    value: 850.00,
    assignedTo: { name: '', email: '' },
    department: '',
    location: 'North Campus - IT Storage',
    description: 'A spare laptop available for assignment.',
    serialNumber: 'AST-005',
    auditLog: [],
  },
  {
    id: 'asset-6',
    assetTag: 'TAG-1006',
    name: 'Epson PowerLite 1781W',
    category: AssetCategory.Projector,
    status: AssetStatus.InRepair,
    purchaseDate: '2021-05-10',
    reimageDate: '',
    value: 749.00,
    assignedTo: { name: '', email: '' },
    department: 'AV Services',
    location: 'AV Repair Bench',
    description: 'Portable classroom projector. Issue: Dim bulb. Sent for repair.',
    serialNumber: 'EPSON-PL-4321',
    auditLog: [],
  },
   {
    id: 'asset-7',
    assetTag: 'TAG-1007',
    name: 'Lenovo ThinkPad X1',
    category: AssetCategory.Laptop,
    status: AssetStatus.AwaitingReimage,
    purchaseDate: '2022-06-15',
    reimageDate: '2024-09-30',
    value: 1800.00,
    assignedTo: { name: '', email: '' },
    department: 'IT Services',
    location: 'IT Service Desk',
    description: 'Returned from faculty, awaiting re-image for new user.',
    serialNumber: 'AST-007',
    auditLog: [],
  },
];

export const INITIAL_USERS: AppUser[] = [
  { id: 'user-1', name: 'Admin User', email: 'admin@nexa.com', role: 'Admin', lastLogin: '2024-05-20', status: 'Active', password: 'password123' },
  { id: 'user-2', name: 'John Doe', email: 'john@nexa.com', role: 'Staff', lastLogin: '2024-05-19', status: 'Active', password: 'password123' },
  { id: 'user-3', name: 'Jane Smith', email: 'jane@nexa.com', role: 'Viewer', lastLogin: '2024-05-15', status: 'Inactive', password: 'password123' },
];
